services:
  api:
    build:
      context: .
      target: build
    image: zulfizupy/expressrwapi:dev
    volumes:
    - ./:/app
    - /app/node_modules
    ports:
     - 3500:3500
    command: npm run dev