services:
  api:
    build:
      context: .
      # can be also build, bet set to dev
      target: dev
    image: zulfizupy/expressrwapi:dev
    volumes:
    - ./:/app
    - /app/node_modules
    ports:
     - 3500:3500
    command: npm run dev